apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: virtualization-csi-driver
  namespace: {{ .Values.guest.csiDriverNamespace }}
spec:
  selector:
    matchLabels:
      app: virtualization-csi-driver-registrar
  template:
    metadata:
      labels:
        app: virtualization-csi-driver-registrar
      name: virtualization-csi-driver
      namespace: default
    spec:
      containers:
        - name: virtualization-csi-driver
          securityContext:
            privileged: true
          image: dev-registry.deckhouse.io/virt/dev/virtualization-csi-driver:latest
          imagePullPolicy: Always
          args:
            - "--debug"
            - "--csi-endpoint=unix:///csi/csi.sock"
          env:
            - name: HOST_NAMESPACE
              value: {{ .Values.host.virtualMachineNamespace }}
            - name: HOST_KUBECONFIG
              value: {{ .Values.host.kubeconfig }}
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: spec.nodeName
          volumeMounts:
            - name: plugin-dir
              mountPath: /csi
            - name: publish-dir
              mountPath: /var/lib/kubelet
              mountPropagation: Bidirectional
            - name: device-dir
              mountPath: /dev
        - name: csi-driver-registrar
          image: gcr.io/k8s-staging-sig-storage/csi-node-driver-registrar:canary
          args:
            - "--v=5"
            - "--csi-address=$(CSI_ENDPOINT)"
            - "--kubelet-registration-path=$(DRIVER_REG_SOCK_PATH)"
            - "--kubelet-registration-path=/var/lib/kubelet/plugins/virtualization.csi.driver.io/csi.sock"
          env:
            - name: CSI_ENDPOINT
              value: "/csi/csi.sock"
            - name: DRIVER_REG_SOCK_PATH
              value: "/var/lib/kubelet/plugins/virtualization.csi.driver.io/csi.sock"
            - name: KUBE_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          volumeMounts:
            - name: plugin-dir
              mountPath: /csi
            - name: registration-dir
              mountPath: /registration
      imagePullSecrets:
        - name: dev-registry-secret
      volumes:
        - name: registration-dir
          hostPath:
            path: /var/lib/kubelet/plugins_registry/
            type: Directory
        - name: publish-dir
          hostPath:
            path: /var/lib/kubelet
            type: Directory
        - name: plugin-dir
          hostPath:
            path: /var/lib/kubelet/plugins/virtualization.csi.driver.io/
            type: DirectoryOrCreate
        - name: device-dir
          hostPath:
            path: /dev
            type: Directory
