apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: virtualization-storage-class
parameters:
  csi.storage.k8s.io/fstype: "ext4"
  dvpStorageClass: "linstor-test-data-r1"
allowVolumeExpansion: true
provisioner: virtualization.csi.driver.io
reclaimPolicy: Delete
volumeBindingMode: Immediate
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: virtualization-storage-class-wait
parameters:
  csi.storage.k8s.io/fstype: "ext4"
  dvpStorageClass: "linstor-thick-data-r1"
allowVolumeExpansion: true
provisioner: virtualization.csi.driver.io
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
