apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-fs-rwo
spec:
  storageClassName: virtualization-storage-class
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
  volumeMode: Filesystem
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: deploy-fs-rwo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: deploy-fs-rwo
  template:
    metadata:
      labels:
        app: deploy-fs-rwo
    spec:
      nodeSelector:
        kubernetes.io/hostname: vm-01
      containers:
        - name: task-nginx
          image: nginx
          ports:
            - containerPort: 80
              name: "http-server"
          volumeMounts:
            - mountPath: "/storage"
              name: storage
      volumes:
        - name: storage
          persistentVolumeClaim:
            claimName: pvc-fs-rwo