apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-block-rwop
spec:
  storageClassName: virtualization-storage-class
  accessModes:
    - ReadWriteOncePod
  resources:
    requests:
      storage: 500Mi
  volumeMode: Block
---
apiVersion: v1
kind: Pod
metadata:
  name: pvc-block-rwop
spec:
  containers:
    - name: task-nginx
      image: nginx
      ports:
        - containerPort: 80
          name: "http-server"
      volumeDevices:
        - devicePath: "/dev/storage"
          name: storage
  volumes:
    - name: storage
      persistentVolumeClaim:
        claimName: pvc-block-rwop