apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-waitforfirstconsumer
spec:
  storageClassName: virtualization-storage-class-wait
  accessModes:
    - ReadWriteOncePod
  resources:
    requests:
      storage: 500Mi
  volumeMode: Filesystem
---
apiVersion: v1
kind: Pod
metadata:
  name: pvc-waitforfirstconsumer
spec:
  containers:
    - name: task-nginx
      image: nginx
      ports:
        - containerPort: 80
          name: "http-server"
      volumeMounts:
        - mountPath: "/storage"
          name: storage
  volumes:
    - name: storage
      persistentVolumeClaim:
        claimName: pvc-waitforfirstconsumer